bool empty=true;
String userName="";
List mapItems=[];
String destinationPlanetName="";//Destination Planet
String currentPlanetName="";//current location
String spaceLineName="";//SpaceShip Companies
String spaceShipQueryList="";//Space Ship Details
int indexLocTapped=0;//planets index
int spaceIndexLocTapped=0;//spaceship company index
int spaceShipSelected=0;//selected space ship index
Future<String> downloadRef="" as Future<String>;
const double fontSc=18;
const double fontTitle=22;
// SPACESHIP VARS
String userLoc="";
String userDest="";
String spaceShipImage="";
int spaceShipLevel=0;
int spaceShipSeat=0;
int spaceShipThrust=0;
String spaceShipType="";